#!/bin/bash
#
# Builds newsman.zip for uploading as a GitHub release.
# Store owners install the CS-Cart addon by uploading this archive via
# Admin > Add-ons > Manage add-ons > Manual installation.
#
# The CS-Cart addon archive contains files laid out relative to the
# CS-Cart install root (app/, design/, var/).
#
# Steps:
#   1. Copies the repo src/ contents to a temporary work dir (becomes zip root)
#   2. Removes dot-directories (.git, etc.) and dot-files
#   3. Removes tools/ and tests/ directories from the addon
#   4. Deletes vendor/ and composer.lock in the addon, runs composer install --no-dev
#   5. Removes composer.lock generated by composer install
#   6. Cleans non-runtime files from vendor packages
#   7. Creates the zip archive with app/, design/, var/ at the root
#
# Usage:
#   ./build-release-zip.sh <repo_dir> <php_binary> <composer_path> <output_zip>
#
# Example:
#   ./build-release-zip.sh /path/to/newsman php8.2 /usr/local/bin/composer /tmp/newsman.zip

set -e

if [ $# -ne 4 ]; then
    echo "Usage: $0 <repo_dir> <php_binary> <composer_path> <output_zip>"
    echo "  repo_dir       — path to the Newsman CS-Cart repo root (contains src/)"
    echo "  php_binary     — PHP binary to use (e.g. php8.2)"
    echo "  composer_path  — path to the Composer binary (e.g. /usr/local/bin/composer)"
    echo "  output_zip     — output path for the .zip archive"
    exit 1
fi

REPO_DIR="$(realpath "$1")"
PHP_BIN="$2"
COMPOSER_PATH="$3"
OUTPUT_ZIP="$4"

if [ ! -d "$REPO_DIR/src/app/addons/newsman" ]; then
    echo "Error: $REPO_DIR/src/app/addons/newsman not found. Is this the correct repo?"
    exit 1
fi

if [ ! -f "$REPO_DIR/src/app/addons/newsman/composer.json" ]; then
    echo "Error: $REPO_DIR/src/app/addons/newsman/composer.json not found."
    exit 1
fi

case "$OUTPUT_ZIP" in
    /*) ;;
    *) OUTPUT_ZIP="$(pwd)/$OUTPUT_ZIP" ;;
esac

echo "Repo dir    : $REPO_DIR"
echo "PHP binary  : $PHP_BIN"
echo "Composer    : $COMPOSER_PATH"
echo "Output      : $OUTPUT_ZIP"
echo ""

# Step 1: Copy src/ contents to a temp directory (becomes zip root).
echo "=== Step 1: Copying src/ contents to temporary directory ==="
TEMP_DIR=$(mktemp -d)
trap 'rm -rf "$TEMP_DIR"' EXIT

WORK_DIR="$TEMP_DIR/newsman"
mkdir -p "$WORK_DIR"
cp -a "$REPO_DIR/src/." "$WORK_DIR/"
ADDON_DIR="$WORK_DIR/app/addons/newsman"
echo "Copied to: $WORK_DIR"
echo ""

# Step 2: Remove dot-directories and dot-files.
echo "=== Step 2: Removing dot-directories and dot-files ==="
find "$WORK_DIR" -mindepth 1 -name '.*' | while read -r entry; do
    rm -rf "$entry"
    echo "Removed: $entry"
done
echo ""

# Step 3: Remove tools/ and tests/ directories from the addon.
echo "=== Step 3: Removing tools/ and tests/ directories ==="
for dir in tools tests; do
    if [ -d "$ADDON_DIR/$dir" ]; then
        rm -rf "$ADDON_DIR/$dir"
        echo "Removed: $ADDON_DIR/$dir"
    fi
done
echo ""

# Step 4: Delete vendor/ and composer.lock, run composer install --no-dev.
echo "=== Step 4: Cleaning vendor and running composer install --no-dev ==="
if [ -d "$ADDON_DIR/vendor" ]; then
    rm -rf "$ADDON_DIR/vendor"
    echo "Deleted: $ADDON_DIR/vendor"
fi
if [ -f "$ADDON_DIR/composer.lock" ]; then
    rm "$ADDON_DIR/composer.lock"
    echo "Deleted: $ADDON_DIR/composer.lock"
fi

cd "$ADDON_DIR"
"$PHP_BIN" "$COMPOSER_PATH" install --no-dev -vvv
echo ""

# Step 5: Remove composer.lock generated by composer install.
echo "=== Step 5: Removing composer.lock ==="
if [ -f "$ADDON_DIR/composer.lock" ]; then
    rm "$ADDON_DIR/composer.lock"
    echo "Deleted: $ADDON_DIR/composer.lock"
fi
echo ""

# Step 6: Clean non-runtime files from vendor packages.
echo "=== Step 6: Cleaning non-runtime files from vendor ==="
VENDOR_DIR="$ADDON_DIR/vendor"

for dir in tests test examples example libs wiki doc docs .github .settings; do
    find "$VENDOR_DIR" -mindepth 2 -maxdepth 3 -type d -name "$dir" | while read -r d; do
        rm -rf "$d"
        echo "Removed: $d"
    done
done

for pattern in phpunit.xml phpunit.xml.dist phpunit.xml.dist.bak .travis.yml .gitignore .gitattributes .gitmodules .buildpath .project .eclipse-PHP-formatter.xml runtest.sh README.md CHANGELOG.md CONTRIBUTING.md; do
    find "$VENDOR_DIR" -mindepth 2 -maxdepth 3 -type f -name "$pattern" | while read -r f; do
        rm "$f"
        echo "Removed: $f"
    done
done
echo ""

# Step 7: Create the zip archive.
echo "=== Step 7: Creating zip archive ==="
[ -f "$OUTPUT_ZIP" ] && rm "$OUTPUT_ZIP"

cd "$WORK_DIR"
zip -r "$OUTPUT_ZIP" . -x ".*"

echo ""
echo "=== Done ==="
echo "Archive created: $OUTPUT_ZIP"
echo "Size: $(du -h "$OUTPUT_ZIP" | cut -f1)"
